name: Release Info
on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, reopened, synchronize, ready_for_review]

jobs:
  check-pr:
    name: Validate PR Release Label and Notes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jefflinse/pr-semver-bump@v1.4.0
        name: Validate PR metadata
        with:
          mode: validate
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          require-release-notes: true
          release-notes-prefix: '^### RELEASE NOTES\s*$'
          release-notes-suffix: '^#{1,3}[^#]'
          with-v: true
