name: Release Info
on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, reopened, synchronize, ready_for_review]

jobs:
  check-pr:
    name: Validate PR Release Label and Notes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jefflinse/pr-semver-bump@b6ca76fbacf15eef7705cfc50542c94145b9f4f4
        name: Validate PR metadata
        with:
          mode: validate
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          require-release-notes: true
          with-v: true
